# Generated by Django 4.0.5 on 2022-06-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='myapp.profile'),
        ),
    ]
